services:
  db:
    image: postgres:15-alpine
    environment:
      POSTGRES_USER: kubsu
      POSTGRES_PASSWORD: kubsu
      POSTGRES_DB: kubsu
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U kubsu"]
      interval: 5s
      timeout: 5s
      retries: 5

  app:
    image: shmadikdocs/kubsu-app:latest
    ports:
      - "8042:8042"
    environment:
      DATABASE_URL: postgresql+psycopg://kubsu:kubsu@db:5432/kubsu
      PORT: "8042"
    depends_on:
      db:
        condition: service_healthy